
# When issue is created with title "Deploy" and anybody
# comment "/deploy" in comment this workflow is triggered.
# This workflow publish the package in @next tag.

name: Process master branch for @next tag

on:
  issue_comment:
    types: [created]

jobs:
  prepare-master:
    if: ${{ github.event.issue.title == 'Deploy' && github.event.comment.body == '/deploy' && github.event.issue.state == 'open' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git config user.name bhoos-devops
          git config user.email devops@bhoos.com
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@bhoos'

      - name: Install Dependencies and publish packages
        run: |
          yarn
          yarn version --patch
          yarn publish . --tag next
          version=$(node -p "require('./package.json').version")
          echo "RELEASE_VERSION=v${version}" >> $GITHUB_ENV
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v1
        with:
          configuration: "workflow_config/config.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release for moving to production
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.RELEASE_VERSION }}
          name: Release ${{ env.RELEASE_VERSION }}
          commit: master
          body: ${{steps.github_release.outputs.changelog}}
          draft: true
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}